config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :performances, only: [ :index, :create, :update, :destroy] do
    resources :bookings, only: [:update]
  end
  resources :bookings, only: [ :create]
  resources :users, only: [:show, :edit, :update] do
    resources :photos, only: [:create]
  end
  resources :photos, only: [:destroy, :edit]
  get "/dashboard", to: "users#dashboard", as: "dashboard"
  patch "/dashboard", to: "bookings#update", as: "booking"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :date, presence: true;
  validates :location, presence:true;
  belongs_to :performance
  belongs_to :customer, class_name: "User", foreign_key: :user_id
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :artist, class_name: "User", foreign_key: :user_id
  has_many :bookings, dependent: :destroy
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def self.descriptions
    Performance.pluck(:description)

  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  mount_uploader :artist_photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, presence: true, uniqueness: true
  has_many :performances
  has_many :bookings
  has_many :photos
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include PgSearch
  pg_search_scope :search_username_performances,
    against: [ :username, :bio, :location],
    associated_against: {
      performances: [ :description, :price ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:home, :show]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  include Pundit


  # Pundit: white-list approach.
   after_action :verify_authorized, except: :index, unless: :skip_pundit?
   after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

   # # Uncomment when you *really understand* Pundit!
   # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
   # def user_not_authorized
   #   flash[:alert] = "You are not authorized to perform this action."
   #   redirect_to(root_path)
   # end

   private

   def skip_pundit?
     devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
   end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.customer = current_user
    @user = User.find(Performance.find(params[:booking][:performance_id]).user_id)
    unless @booking.save
      render 'users/show'
    end
  end

  def update
    @booking = Booking.find(params[:booking][:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to dashboard_path
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:performance_id, :date, :location, :work_asked, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @users = User.where(is_artist: true)
    if params[:query] && params[:query] != ''
      @users = @users.search_username_performances(params[:query])
    end
    # raise

    #   @users = User.joins(:performances).where("performances.description LIKE ?", params[:query])
    # end
  end
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  def show
    @performance = Performance.find(params[:id])
    authorize @performance
    @booking = Booking.new
  end

  def create
    @performance = Performance.new(performances_params)
    @performance.artist = current_user
    authorize @performance
    @performance.save
    current_user.is_artist = true
    current_user.save
    redirect_to edit_user_path(current_user)
  end

  def destroy
    @performance = Performance.find(params[:id])
    authorize @performance
    @performance.destroy
    redirect_to edit_user_path(current_user)
  end

  private

  def performances_params
    params.require(:performance).permit(:price, :description)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user
    authorize @photo
    @photo.save
    redirect_to edit_user_path(current_user)
  end

  def destroy
    @photo = Photo.find(params[:id])
    authorize @photo
    @photo.destroy
    redirect_to edit_user_path(current_user)
  end

  private

  def photo_params
    params.require(:photo).permit(:artist_photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_after_action :verify_authorized, only: :show

  def show
    @user = User.find(params[:id])
    @booking = Booking.new
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
    @performance = Performance.new
    @photo = Photo.new
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    @user.update(user_params)
    redirect_to edit_user_path
  end

  def dashboard
    @user = current_user
    authorize @user
    @my_orders = current_user.bookings.order(status: :DESC)
    @my_bookings = Booking.joins(:performance).where(performances: { user_id: current_user.id }).order(status: :DESC)
  end

  private

  def user_params
    params.require(:user).permit(:bio, {photos: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pimp my wall</title>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

  </head>

  <body>
    <%= render "shared/login_modal" %>
    <%= render "shared/signup_modal" %>
    <div class="wrapper">
      <div class="content">
        <%= render 'shared/navbar' %>
        <%= render 'shared/flashes' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application', "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://bit.ly/2HwhFdx');">
  <div class="banner-content">
    <h1>Pimp My Wall</h1>
    <h2>Make your wall unique</h2>
    <div class="search-form" >
      <%= form_tag root_path, method: :get do %>
      <div class="input-group">
        <input type="text" class="form-control" id="input-home-search" placeholder="Wall painting..." name="query">
        <span class="input-group-btn">
          <button class="btn btn-eucalyptus" type="button" id="btn-home-search" >Search</button>
        </span>
      </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @users.each do |artist| %>
      <div class="col-xs-12 col-sm-6 col-lg-6">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.1)), url('<%= cl_image_path artist.photos.first.artist_photo%>')" >
          <div class="card-content" >
            <div class="username">
              <p>by <%= link_to "#{artist.username}", user_path(artist) %></p>
            </div>
            <div class="avatar">
              <%= image_tag artist.avatar, alt:"avatar", class: "avatar_circle" %>
            </div>
            <div class="location">
              <p><i class="fas fa-map-marker-alt"></i> <%= artist.location %></p>
            </div>
          </div>
          <a class="card-link" href=<%= user_path(artist) %>></a>
        </div>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This app was made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content text-center">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Sign in</h5>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name),html:{id:'form-login-modal'}) do |f| %>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", id:'email-login' %>
          </div>

          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "off", id:'password-login' %>
          </div>

          <% if devise_mapping.rememberable? -%>
            <div class="field">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
          <% end -%>

          <div class="actions">
            <%= f.submit "Log in", class:"btn-eucalyptus" %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <% if current_user.is_artist %>
        <%= link_to "Dashboard", dashboard_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>

        <%= link_to "My page", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>


      <% else %>
        <%= link_to "Commandes", dashboard_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
        <div class="artist-btn-wrapper">
          <%= link_to "Are you an Artist ? ", edit_user_path(current_user), class: "artist-btn" %>
        </div>
      <% end %>







      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

          <%= image_tag current_user.avatar, alt:"avatar",class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>



          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Sign up", "#sign-up", "data-toggle" => "modal", class: 'navbar-wagon-item navbar-wagon-link' %>
      <%= link_to "Sign in", "#login", "data-toggle" => "modal", class: 'navbar-wagon-item navbar-wagon-link' %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_signup_modal.html.erb
<div class="modal fade" id="sign-up" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content text-center">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Sign up</h5>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div class="field">
            <%= f.label :username %><br />
            <%= f.text_field :username, autofocus: true, autocomplete: "username" %>
          </div>

          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>

          <div class="field">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off" %>
          </div>

          <div class="field">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off" %>
          </div>

          <div class="actions">
            <%= f.submit "Sign up", class:"btn-eucalyptus" %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container">
  <% if @my_bookings.count > 0 %>
    <div class="bookings">
      <h1>My Bookings</h1>
      <ul class="list-unstyled row">
        <% @my_bookings.each do |booking| %>
          <li>
            <div class="col-xs-12 col-sm-6 col-lg-4">
              <div class="card-order card-booking">
                <%= link_to(user_path(booking.customer)) do %>
                <%= image_tag booking.customer.avatar, class: "avatar-dash"%>
                <% end %>
                <div class="card-username">
                  <%= booking.customer.username %>
                </div>
                <div class="card-work">
                  <h3><%= booking.performance.description %></h3>
                  <%= booking.work_asked %>
                  <div class="map">
                    <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=300x200&sensor=false&maptype=roadmap&markers=color:red%7C#{booking.location}&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
                  </div>
                </div>
                <div class="card-price-status">
                  <h2><%= booking.performance.price %> €</h2>
                  <% if booking.status == "Accepted" %>
                    <h2 class="status-accepted">Accepted</h2>
                  <% elsif booking.status == "Pending" %>
                    <h2 class="status-pending">Pending</h2>
                  <% elsif booking.status == "Declined"%>
                    <h2 class="status-declined">Declined</h2>
                  <% else %>
                    <h2 class="status-cancelled">Cancelled</h2>
                  <% end %>
                </div>
                <div class="validation">
                  <% if booking.status == "Pending" %>
                    <div>
                      <%= simple_form_for(booking, url: booking_path, method: "patch") do |f| -%>
                        <%= f.input :status, input_html: {value: "Accepted"}, as: :hidden%>
                        <%= f.input :id, value: booking.id, as: :hidden %>
                        <%= button_tag type: 'submit', class: "submit-icon", data: { toggle: 'tooltip', placement: 'bottom', title: 'Accept'} do %>
                          <i class="fa fa-check"></i>
                        <% end %>
                      <% end -%>
                    </div>
                    <div>
                      <%= simple_form_for(booking, url: booking_path, method: "patch") do |f| -%>
                        <%= f.input :status, input_html: {value: "Declined"}, as: :hidden%>
                        <%= f.input :id, value: booking.id, as: :hidden %>
                        <%= button_tag type: 'submit', class: "submit-icon", data: { toggle: 'tooltip', placement: 'bottom', title: 'Decline'} do %>
                          <i class="fa fa-times"></i>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>
                  <% if booking.status == "Accepted" %>
                    <%= simple_form_for(booking, url: booking_path, method: "patch") do |f| -%>
                      <%= f.input :status, input_html: {value: "Cancelled"}, as: :hidden%>
                      <%= f.input :id, value: booking.id, as: :hidden %>
                      <%= button_tag type: 'submit', class: "submit-icon", data: { toggle: 'tooltip', placement: 'bottom', title: 'Cancel booking'} do %>
                        <i class="fa fa-ban"></i>
                      <% end %>
                    <% end -%>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="orders">
    <h1>My Orders</h1>
    <ul class="list-unstyled row">
      <% @my_orders.each do |order| %>
        <li>
          <div class="col-xs-12 col-sm-6 col-lg-4 ">
            <div class="card-order">
              <%= link_to(user_path(order.performance.artist)) do %>
                <%= image_tag order.performance.artist.avatar, class: "avatar-dash"%>
              <% end %>
              <div class="card-username">
                <%= order.performance.artist.username %>
              </div>
              <div class="card-work">
                <h3><%= order.performance.description %></h3>
                <p><%= order.location %></p>
                <%= order.work_asked %>
              </div>
              <% if order.status == "Pending" %>
                <div class="card-price-status">
                  <h2><%= order.performance.price %> €</h2>
                  <h2>Pending</h2>
                </div>
              <% else %>
                <div class="card-price-status">
                  <h2><%= order.performance.price %> €</h2>
                  <% if order.status == "Accepted" %>
                    <h2 class="status-accepted">Accepted</h2>
                  <% elsif order.status == "Declined" %>
                    <h2 class="status-declined">Declined</h2>
                  <% else %>
                    <h2 class="status-cancelled">Cancelled</h2>
                  <% end %>
                </div>
              <% end %>
              <div class="validation">
                <% if order.status == "Accepted" %>
                  <%= simple_form_for(order, url: booking_path, method: "patch") do |f| -%>
                    <%= f.input :status, input_html: {value: "Cancelled"}, as: :hidden%>
                    <%= f.input :id, value: order.id, as: :hidden %>
                    <%= button_tag type: 'submit', class: "submit-icon", data: { toggle: 'tooltip', placement: 'bottom', title: 'Cancel booking'} do %>
                      <i class="fa fa-ban"></i>
                    <% end %>
                  <% end -%>
                <% end %>
                <% if order.status == "Pending" %>
                  <%= simple_form_for(order, url: booking_path, method: "patch") do |f| -%>
                    <%= f.input :status, input_html: {value: "Cancelled"}, as: :hidden%>
                    <%= f.input :id, value: order.id, as: :hidden %>
                    <%= button_tag type: 'submit', class: "submit-icon", data: { toggle: 'tooltip', placement: 'bottom', title: 'Cancel request'} do %>
                      <i class="fa fa-ban"></i>
                    <% end %>
                  <% end %>
                <% end %>
                <% if order.status == "Declined" %>
                  <div class="btn btn-declined-order">
                    <%= link_to "Let's find someone else!", root_path %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<!-- HEADER -->
<% if @user.photos.empty?%>
  <div class="header-edit" style="background-color: rgba(150, 150, 150, 0.9)">
<% else  %>
  <div class="header-edit" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.5)), url('<%= cl_image_path @user.photos.first.artist_photo %>')">
<% end  %>
    <%= image_tag @user.avatar, alt: "Avatar", class: "avatar-edit" %>
  <div class="header-text">
      <h1> <%= @user.username %> </h1>
      <p> - <em>Edit here your own profile page</em> 🤔</p>
  </div>
</div>


<!-- BIO CARD -->
<div class="container">
  <div class="wrapper-edit">
    <div class="row">
      <div id="bio-text">
        <div class="title-card">
          <h2> My Bio </h2>
          <%= link_to "", "#", class: "fas fa-pen-square edit-pen", id:"edit-bio-btn" %>
        </div>
        <p> <%= @user.bio %> </p>
      </div>
      <div id="edit-form-bio" class="text-center edit-forms hidden">
        <%= simple_form_for(@user) do |f| %>
          <%= f.input :bio %>
          <%= f.submit class: "btn btn-eucalyptus"%>
        <% end %>
      </div>
    </div>
  </div>

<!-- PERF CARD -->
    <div class="wrapper-edit">
        <div class="title-card">
         <h2> My Perfs</h2>
        </div>

        <div class="container-fluid">
          <div class="row">
            <%  @user.performances.each do |performance|%>
              <div class="col-xs-3">
                <div class="card-performance">
                  <h3> <%=  performance.description %> </h3>
                  <h4> <%= performance.price %> €</h4>
                  <div class="edit-btns">
                    <!--<%= link_to "", "#", class: "fas fa-pen-square edit-pen" %> -->
                    <%= link_to "", performance_path(performance), method: :delete, class: "fas fa-times-circle trash-btn-red" %>
                  </div>
                  <div id="edit-perf-form" class="card-performance hidden">
                    <%= simple_form_for(performance) do |f| %>
                      <%= f.input :description %>
                      <%= f.input :price %>
                      <%= f.submit "Create Performance", class: "btn btn-eucalyptus" %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
            <div class="col-xs-6 col-md-3">
              <div class="card-photos">
                <div class= "photo-style" style= "background-image : linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1516962080544-eac695c93791?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=4ed529e5822ea78a3b0056c725e5d7b3&auto=format&fit=crop&w=668&q=80'); background-position: center; background-size: cover;" >
                  <div class="overlay" id="overlay-add">
                    <div class="delete-photos">
                        <%= link_to "", "#", class: "fas fa-plus-square trash-btn-grey", id: "create-perf-btn" %>
                        <p>Add Performance</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- end of first row -->
          <div class="row">
            <div id="add-perf-form" class="text-center edit-forms hidden">
              <%= simple_form_for(@performance) do |f| %>
              <%= f.input :description %>
              <%= f.input :price %>
              <%= f.submit "Create Performance", class: "btn btn-eucalyptus" %>
            <% end %>
            </div>
          </div>
        </div>

    </div>


<!-- MY PHOTOS CARD -->
    <div class="wrapper-edit">
      <div class="title-card">
        <h2> My Photos</h2>
      </div>



      <div class="container-fluid ">
      <div class="row">
            <% @user.photos.each do |photo|%>
            <div class= "col-xs-6 col-md-3">
              <div class="card-photos">
                <div class= "photo-style" style= "background-image : url('<%= cl_image_path photo.artist_photo %>')"></div>

                <div class="overlay">
                  <div class="delete-photos">
                  <%= link_to "", photo_path(photo), method: :delete, class: "fas fa-times-circle trash-btn-grey" %>
                  <p> Delete </p>
                  </div>
                </div>
              </div>
            </div>
              <% end %>

            <div class="col-xs-6 col-md-3">
              <div class="card-photos">
                <div class= "photo-style" style= "background-image : linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1505840541251-02ab21f95b45?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=42ff8682cf27a5e78548f9523ed29d4d&auto=format&fit=crop&w=632&q=80'); background-position: center;">
                  <div class="overlay" id="overlay-add">
                    <div class="delete-photos">
                        <%= link_to "", "#", class: "fas fa-plus-square trash-btn-grey", id: "add-photo-btn" %>
                        <p>Add Photo</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
      </div>

    <div class="row">
      <div class="text-center edit-forms hidden" id="add-photo-form">
        <%= simple_form_for([@user, @photo]) do |f| %>
          <!-- [...] -->
          <%= f.input :artist_photo%>
          <%= f.input :artist_photo_cache, as: :hidden %>
          <!-- [...] -->
          <%= f.submit "Add Photo", class: "btn btn-eucalyptus" %>
        <% end %>
      </div>
    </div>
  </div>
</div>